spring:
  datasource:
    url: jdbc:mysql://hyuniklog-database.cxqgttg1ggis.ap-northeast-2.rds.amazonaws.com:3306/hyuniklog_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: ekffld5465
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
